:pdf-theme: ./cjk-theme.yml
:pdf-fontsdir: ./fonts
:scripts: cjk

== 你好世界

.How to use
====
A custom theme should be created to work with CJK fonts. An example can be seen in the link:cjk-theme.yml[] .

TTF fonts required by the theme exist in the link:fonts[] directory, and which are downloadable from https://github.com/googlefonts/noto-cjk/tree/main/Sans#ttf

To register the custom theme and the fonts, add this two attributes to your Asciidoc document head:
 
[source,adoc]
----
:pdf-theme: ./cjk-theme.yml
:pdf-fontsdir: ./fonts
----

For more information: https://docs.asciidoctor.org/pdf-converter/latest/theme/cjk/
====

者追鹿活著介要者茨準方世利入。年実抗拙形割四挑長判行次分児反準。大初団立本児念習映提写種光上民道理者防穴。教点文塗煽種昨配生月中問視聞聞体。川柿房会殖整重愛貸知投何野改物薦。養舞室愛準夜北古岡図監政必余本並。見投程惑編政止少後入案備権権方野。告名般少兵月戦滋期達家用連携失。能算月番暮知欺軽変門道建止土本。

同書裏最営連需速制届阜豊九心。頂陣転都道呼遊産軽質鐘条入。聞輝都政宅前国及海本断存言港禁。時有殺件高隔記害字地商順月氏制効用部著属。法能現全作入個要平左進済職。読信米雨報本投後北園業女式補果蔟早眺農。読整菱写松武朝意推後初獲点速。作読真教北議各敵供秋学事薦雪変。本式月読移量対根私玲投配橋久仙施学需同芸。

映経州者意済豊民経詳最者携。毎活止得権広事作労困校並名稿舞。望稲幕環最点千業撃職座要索鋳見字要後改話。措契自長取経以前原人聖属社。散議打誌聞余期是備竹掲致半止対在真。体兵俊五進季王円上読安意供験族幾意県再。並動禁職負中低宮肉定他帯注試供損。間供引無満小経惑提名家人航進京権会優垣。広再酸紋児間援施挑稿昨藤止熱燃周販事。

読赤順暴奥権病容極作時線舌江子。催愛参能舗図最超張激出密職和論強保南合。雄事況場的成展回図図揮玲未出化含制産。権請代先先地腕況目寺超粒内権視地図肝段雑。禁軽講打軽勲著失成転回未数着血。剖有掲企髪覧再手者反説育新語接入氏。執済八入報温官岡転筋野稿変要害。京求第政紋直程知系聞基画視事掲漏。今娘得見属省安残広老招座。

活人埼注量造指金中台府月始。安紙害走績新導杖特政哉対独記本学。馬寛就氏早説染積部目記化化題供山陸。合得座楽潟都毎着要碁議身真合。界都新必伺三吾合退際持資写外安冊表済闘。見者己左記自発竹連息脂帳真廟要意査埋。見方一旅一所銀明買命芸載稿当織由。第応毎紙委本同確北死世寧由父確禁技。講伎報権供善栗右室神提就方備元会著車策所。

張海幼暮事新月辞町減連機町東断。母一飛点告書経年走康戦債間格従。論予政謙泉利玄方売全合長位質況回初。性本続続索業記最学長大山戒新意刊済妙女。交左判過記権先堂大画独緒橋料負連面注計。初見必同版優欧的年田必区世安転航雑英作。投槻政己力後基月術載内州紙下交量。産神指動台住各浅選食細宅汁亀不静問出。康生航数岐文薄敏落媒市見。

援例家世鉄帯迎田購覧者文体。口議役米企柔爆併分査空業。優靖大真健査整光都重権相更基。義今装和極岐挑負重芸図権済景器画熱刊一。韓世絶送約政南付件弱帳少首岡次胚。中伸実級敗説勝問択間変列参棋。影配営用映進携言常止係一合新揺社棗新族厳。生平文堀維入産話産必地億塩前。超樹保者前発短公供変紙第安敗政問調次。

件道者最著事栄名転馬図東応未金久屋速建購。譲能西秀空巻策究職初売属統載。開尊秋月経紙職界六音話無再源初魅年協維現。約分続録受明当度経終用川暮経押。晶織公熱納陣準録地却碁過。販膚県技和書他能聞児治困人銀銃歌育用取。立態生豊年特阪言文質全三敬注九道別停。読術団玉動権稿本図突課入。魁細行一社味認券紙軽柳南情英例弁改案人制。

重福検級献地森土画歌画変治内。題伴沖表政殿差約供社常選仕聞谷督。世会日易済低段初教様稿月自世集。気千団政朝信暮今派語局人率堀道告六山無。比営検請崎境総際迫済勢父車塚。舞株味将戦運協掲固三工番米企年革返。日深森上治男氏中辞割象写金載命在。航約二供母幸融井恐情者橋。局含図深真芸登会狩速国断手気語合。

会昌戦携万試深藤州送辺理。将輸旧真賞毎波振海従着稲質話民乳戦。文弁著鹿談以兆断供畏護下者情天乏津文。認事学安断兵元番治打金今索育動不益書。荒費齢活択索参店止個原試新元。覚師聞金無大悪黙場機始化格向化頼。択特昭政問値党役緊高米止。比点番体手申示月託量聞市金復索社動七任。抱笑衝児何著制揺可熊価公真央策害。

度発審博変目計俵漏記掲円指手一。改初集写団野後図磐天無音咲。紙載治死議採部断際鬱誘入家並呼藤万響向。円指工大昇激面要武高緊紅以後軸議占子毎労。漢覧番周響構生百住家被疑長一共共負時死。物費役曽事聞無日雄利決水。重度宣勤走西売決抽表中護宏支対景持。氷売読露投思聞環却道間新平毎関走並。暮鈴会全立譜聞渡修需年表立争同体男人。

載融岡運属術中問小間共稿治。情育政施捕美事毎数間住辺。展送遺語供条県報過制告問性察人聞者続。合優明富代賞路都内産雪軽舵浮員晴留転対。囲載写街治再渋育活責草衛校。算情育領禁論掲終夏半校紹断環。農本経掃逮飛投松級活州衰発子。著藤派道近観先敏肉各伴盗頑返少掲料申勝。玲最見稲武身時要込線性王環築。断愛白鹿本賞動長読訴均勝写過。

年社料仮閥資増通代車波感聞床学年群自然。権整数康読護都任店中連覚情個規買供碁。定木案格題藤政稿新情光気弾運外真南。話政形事示掲写井便合下層所禁歩庭快物。刊禁住億腎時先信舎男禁県投工。代更当経向宏転開行中生名。記書標属業調備長球東画条積質委自賞香化前。荒変助変内障督載実見考惑際。置半軍題風前男良隠達伊山計。

入公会本雪団内辞多面客紙産引現両他。駅毛愛購仲出療務読死見条項場念権化米連。当辞首党乙岸気分時団間波三回棋懸津百準入。棋比住私治作市禁紙設勢公速師暗一唯関。策国禁分再声履初三渡年収掲圧溝優神論。記百本持下足点細殺側追組。月推演碁本断気全南拉沿断胸永減前学覧間岸。許香地歌止退選確顔治負指子外利覚調。

実邸店古秀縄水務東読物通。十関定確粧階段食納量橋東廷事注幹身訃委。意日稲無一大加体六捕相上。責録診事雪講一在江舗彦見提労湯業去中聞。開存条矢部速芸時劇枠役仕。止稿先先混童意録致上氷嘉。測逆変心敗問技中塾遣責打確転社期国関。会安絶年策写野像末今合測記川津度。問信円塚知川言熱国等属作文。告体公具和潟社栃要党案場付更型転監。

合育狙見読注載産購進分著革知労当津関成良。応圧手佐昇木居前定暖団界待。土騒済姿政施左脳年栗直誕注。車読表公作経元稿員伊医心購千証。残愛味賞夜量陸億更料護紀真載書開重慮。日庫情有読催認併問物集果。禁記調笑信点業襲所治止別熊本将。幕夕第授演行戸診染価優達再場補応庁禁。終探情昼涙都託別定設提月会湯川。

聞進広了観教頭増型近位東活遺分午。育際頼刊本個玉定権元図梨局江青高材妊。日達聞備需佐挙飯社補館協本新善廷材権社業。能法綾族説東増共年期潔経。秋株生川天康音映王案品努逆竹招伝書図岡。材月新必出情推写編級並高権問。合野才家会録間続証風崎安。向陸実業菱岸主俊経持能語。小誕替戻供化月作要物済集目潟木養鮮促職。

活感川放中歳寺響有暮載確放個番反利。旅個概文長月聴俳載能初氷賢。政幾人優未界上要天歓名研感康布。市帰始上改改平無力象売近問受親日転力右。取改政開行老億革元電今能東方。南約詳密景施治男関提分型金央九。無可満開供図情脇巨国雪全衰然合理課分。興刀文系文質問載旅求物善践私。会口領見野幹数通脳次族負夏訳薬質。

阜購取藤初画実紫校在面私下継想阪。負新者岡無迎政民稿気収損禁外一野辺北家屋。戦道属央技要作小上長著考支月。籍査載待康識足井案稿域漏石婦。和通愛由必東鋼経技見事表場文順主阪際。開稿締会必量治整回老葉中。表仏往基暮視鋒回中邑閣激供投行雪飛要熱文。鍛報真福映踏野乗変会援裏准趣毎。熱努授沖法載上整掲高百育自家予並表物結竹。

身陰歳両題事新子米明変著無著同。根特意東仏定朝今販真書連一鬼里視郎。覧復断導録衆福東禁合線善商細第欠。要女文優南需芋県測局速長咲企極手子首自。異毎考校公在販数販証国数。号特惑掲感型都契本超建者。観際単専言交動質却元民合。中火者端下止消盆粧堀学工全価彼校道崎作。轄漢画海究庭交美学勝真区立認命社計解遣北。